// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcqualcsnbtiekulrpik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcXVhbGNzbmJ0aWVrdWxycGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzAzMzMsImV4cCI6MjA3MDUwNjMzM30.HzRcEYrlvl4AlzVx4Y8CsJ4HzXdXkSk90yvjyk6An6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});